# Generated by Django 4.2.11 on 2024-05-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('live', models.CharField(max_length=150)),
                ('created', models.CharField(max_length=100)),
            ],
        ),
    ]
