# Generated by Django 4.2.13 on 2024-05-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcollector_app', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(verbose_name='feedback date'),
        ),
    ]
