# Generated by Django 4.2.13 on 2024-05-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcollector_app', '0003_tag_alter_feedback_options_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
