# Generated by Django 4.2.13 on 2024-05-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcollector_app', '0004_alter_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='projectcollector_app.tag'),
        ),
    ]
